ALTER USER 'root'@'localhost' IDENTIFIED BY 'RevNor';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'RevNor';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED BY 'RevNor';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;
